import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('docs/screenshots', { recursive: true });
const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || 'chromium' });
const log = [];
try {
  for (const [width, height] of [[1280, 800], [840, 800], [400, 820], [360, 480], [700, 800], [1100, 800]]) {
    const context = await browser.newContext({ viewport: { width, height }, permissions: ['clipboard-read', 'clipboard-write'] });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push(`${m.text()} ${m.location().url}`); });
    await page.goto('http://127.0.0.1:5173');
    await page.locator('.item-row').first().waitFor();
    await page.evaluate(() => document.fonts.ready);
    assert.equal(await page.locator('.item-row').count(), 636);
    assert.equal(await page.getByRole('button', { name: '切换竖版', exact: true }).isDisabled(), true);
    assert.equal(await page.locator('.titlebar').evaluate(e => e.scrollWidth > e.clientWidth), false);
    if (width < 700) await page.locator('#item-10001 .item-row').click();
    if (process.env.TEST_SCREENSHOTS !== '0') await page.screenshot({ path: `docs/screenshots/${width}x${height}.png`, animations: 'disabled' });
    const overflow = await page.evaluate(() => [...document.querySelectorAll('.toolbar,.catalog,body')].some(e => e.scrollWidth > e.clientWidth));
    assert.equal(overflow, false, `${width}: horizontal overflow`);
    assert.equal(await page.locator('.item-icon img').first().evaluate(i => i.complete && i.naturalWidth > 0), true);
    await page.keyboard.press('Control+k');
    await page.keyboard.type('TJZBD');
    assert.equal(await page.locator('.item-row').count(), 1);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.item-row').count(), 636);
    await page.getByRole('group', { name: '品质', exact: true }).getByRole('button', { name: '紫色' }).click();
    assert((await page.locator('.item-row').count()) > 0);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.item-row').count(), 636);
    await page.locator('#item-10001 .item-row').click();
    await page.getByRole('button', { name: '收藏', exact: true }).click();
    await page.getByRole('button', { name: '☆ 收藏', exact: true }).click();
    assert.equal(await page.locator('.item-row').count(), 1);
    await page.waitForFunction(() => JSON.parse(localStorage.getItem('fuyou.filters') || '{}').favorites && JSON.parse(localStorage.getItem('fuyou.favorites') || '[]').includes('10001'));
    await page.reload();
    await page.locator('.item-row').first().waitFor();
    assert.equal(await page.locator('.item-row').count(), 1);
    if (width < 700) await page.locator('.item-row').first().click();
    await page.getByRole('button', { name: '复制效果文本' }).click();
    assert((await page.evaluate(() => navigator.clipboard.readText())).startsWith('铁剑在必得（橙色·通用）'));
    await page.keyboard.press('Escape');
    await page.keyboard.press('Control+k');
    await page.keyboard.type('no-such-fuyou');
    assert.equal(await page.getByText('没有匹配的福佑', { exact: true }).count(), 1);
    await page.getByRole('button', { name: '清除筛选', exact: true }).click();
    await page.getByRole('group', { name: '范围', exact: true }).getByRole('button', { name: '专属', exact: true }).click();
    await page.getByRole('button', { name: '全部英雄', exact: true }).click();
    await page.getByRole('textbox', { name: '搜索英雄' }).fill('亚巴顿');
    await page.getByRole('button', { name: '亚巴顿', exact: true }).click();
    assert((await page.locator('.item-row').count()) > 0);
    assert.equal(await page.locator('.toolbar').evaluate(e => e.scrollWidth > e.clientWidth), false);
    await page.keyboard.press('Escape');
    await page.locator('.catalog').click({ position: { x: 3, y: 3 } });
    await page.keyboard.type('gsx');
    assert.equal(await page.getByRole('searchbox').inputValue(), 'gsx');
    assert.equal(await page.locator('.item-name strong').first().textContent(), '攻速鞋');
    await page.keyboard.press('Escape');
    await page.keyboard.press('ArrowDown');
    const selected = await page.locator('.item.selected').getAttribute('id');
    assert.notEqual(selected, 'item-10001');
    if (width < 700) {
      await page.keyboard.press('Enter');
      assert.equal(await page.locator('.expanded').count(), 1);
      await page.keyboard.press('Enter');
      assert.equal(await page.locator('.expanded').count(), 0);
    }
    await page.getByRole('button', { name: '模拟器', exact: true }).click();
    await page.getByRole('heading', { name: '福佑模拟器', exact: true }).waitFor();
    assert.equal(await page.getByRole('spinbutton', { name: '模拟移动速度' }).count(), 0);
    assert.equal(await page.getByRole('button', { name: '应用移速', exact: true }).count(), 0);
    assert.equal(await page.locator('.sim-results button').count(), 636);
    assert.equal(await page.getByRole('button', { name: '显示更多', exact: true }).count(), 0);
    const lastResult = page.locator('.sim-results button').last();
    const lastId = await lastResult.getAttribute('data-id');
    await lastResult.click();
    assert.equal(await lastResult.getAttribute('aria-pressed'), 'true');
    const selectedScroll = await page.locator('.sim-results').evaluate(e => e.scrollTop);
    await lastResult.click();
    assert.equal(await lastResult.getAttribute('aria-pressed'), 'false');
    assert.equal(await page.locator(`.sim-card[data-id="${lastId}"]`).count(), 0);
    assert.equal(await page.locator('.sim-results').evaluate(e => e.scrollTop), selectedScroll);
    await lastResult.press('Space');
    assert.equal(await lastResult.getAttribute('aria-pressed'), 'true');
    await lastResult.press('Enter');
    assert.equal(await lastResult.getAttribute('aria-pressed'), 'false');
    await page.getByRole('textbox', { name: '搜索模拟福佑' }).fill('gsx');
    await page.waitForFunction(() => document.querySelector('.sim-results')?.scrollTop === 0);
    await page.getByRole('textbox', { name: '搜索模拟福佑' }).fill('');
    assert.equal(await page.locator('.sim-results button').count(), 636);
    assert.equal(await page.getByRole('button', { name: '显示悬浮图标', exact: true }).count(), 0);
    assert.equal(await page.getByRole('button', { name: '开始采集', exact: true }).count(), 0);
    await page.getByRole('textbox', { name: '搜索模拟福佑' }).fill('玻璃大炮');
    await page.locator('.sim-results button').filter({ hasText: '10027a' }).click();
    assert((await page.locator('.stat-tile').filter({ hasText: '伤害输出加成' }).textContent()).includes('+37.5%'));
    const selectedCard = page.locator('.sim-card[data-id="10027a"]');
    assert.equal(await selectedCard.locator('.sim-effect').count(), 1);
    assert.equal(await selectedCard.locator('details').count(), 0);
    const roll = selectedCard.locator('.inline-roll input');
    await roll.fill('9999');
    assert.equal(await roll.getAttribute('aria-invalid'), 'true');
    await roll.blur();
    assert.equal(await roll.inputValue(), await roll.getAttribute('max'));
    await roll.fill('-1');
    await roll.blur();
    assert.equal(await roll.inputValue(), await roll.getAttribute('min'));
    await roll.fill('45');
    await page.waitForFunction(() => document.querySelector('.sim-summary')?.textContent.includes('+45%'));
    await page.getByRole('textbox', { name: '搜索模拟福佑' }).fill('gsx');
    await page.locator('.sim-results button').first().click();
    const movementInput = page.locator('.sim-card[data-id="10006"]').getByRole('spinbutton', { name: '模拟移动速度' });
    await movementInput.fill('300');
    await page.waitForFunction(() => document.querySelector('.sim-summary')?.textContent.includes('+27点'));
    await movementInput.fill('-1');
    assert.equal(await movementInput.getAttribute('aria-invalid'), 'true');
    assert(!(await page.locator('.sim-summary').textContent()).includes('+27点'));
    await movementInput.fill('');
    assert((await page.locator('.sim-summary').textContent()).includes('攻速鞋未计入'));
    await movementInput.fill('0');
    assert(!(await page.locator('.sim-summary').textContent()).includes('攻速鞋未计入'));
    await movementInput.fill('300');
    assert((await page.locator('.stat-tile').filter({ hasText: '额外攻击速度' }).textContent()).includes('+27点'));
    await page.waitForFunction(() => JSON.parse(localStorage.getItem('fuyou.simulator.v1') || '{}').movement === 300);
    await page.reload();
    await page.getByRole('button', { name: '模拟器', exact: true }).click();
    assert.equal(await page.locator('.sim-card').count(), 2);
    assert((await page.locator('.sim-summary').textContent()).includes('+45%'));
    await page.getByRole('textbox', { name: '搜索模拟福佑' }).fill('技能增强');
    await page.getByLabel('模拟品质', { exact: true }).selectOption('1');
    await page.getByLabel('模拟范围', { exact: true }).selectOption('common');
    assert((await page.locator('.sim-results button').count()) > 0);
    if (process.env.TEST_SCREENSHOTS !== '0') await page.screenshot({ path: `docs/screenshots/simulator-${width}x${height}.png`, animations: 'disabled' });
    assert.equal(await page.locator('.simulator').evaluate(e => e.scrollWidth > e.clientWidth), false);
    await page.getByRole('button', { name: '清空方案', exact: true }).click();
    assert.equal(await page.locator('.sim-card').count(), 0);
    await page.getByRole('button', { name: '撤销清空', exact: true }).click();
    assert.equal(await page.locator('.sim-card').count(), 2);
    await page.getByRole('button', { name: '移除攻速鞋', exact: true }).click();
    assert.equal(await page.locator('.sim-card').count(), 1);
    await page.keyboard.press('Control+k');
    await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === '搜索福佑');
    if (width < 700) {
      await page.locator('#item-10001 .item-row').click();
      await page.keyboard.press('ArrowDown');
      await page.waitForFunction(() => document.activeElement?.closest('.item')?.id === document.querySelector('.item.selected')?.id);
      await page.keyboard.press('Enter');
      assert.equal(await page.locator('.item.selected .expanded').count(), 1);
    }
    await page.getByRole('button', { name: '队友', exact: true }).click();
    await page.getByRole('heading', { name: '队友红黑榜', exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: '导入玩家／匹配截图' }).isDisabled(), true);
    assert.equal(await page.locator('.roster').evaluate(e => e.scrollWidth > e.clientWidth), false);
    assert.deepEqual(errors, []);
    log.push(`PASS ${width}x${height}: catalog regression, no overflow/console errors, offline simulator selection, midpoint/override, movement, persistence, filters, remove, clear/undo; legacy live controls hidden.`);
    await context.close();
  }
} finally { await browser.close(); }
console.log(log.join('\n'));
await writeFile('docs/screenshots/acceptance.txt', log.join('\n') + '\n');
