import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { resolve } from 'node:path';
import { readFile, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
if (process.platform === 'win32' && /dota2\.exe/i.test(execFileSync('tasklist.exe', ['/FI', 'IMAGENAME eq dota2.exe', '/FO', 'CSV', '/NH'], { encoding: 'utf8', windowsHide: true }))) throw new Error('Native window checks must wait until Dota 2 is closed.');
const profile = await mkdtemp(join(tmpdir(), 'fuyou-electron-'));
const executablePath = process.env.FUYOU_EXECUTABLE;
const profileArgument = `--user-data-dir=${profile}`;
const options = executablePath ? { executablePath, args: [profileArgument] } : { args: [resolve('.'), profileArgument] };
let app;
try {
  app = await electron.launch(options);
  const page = await app.firstWindow();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.locator('.item-row').first().waitFor();
  assert.equal(await page.locator('.item-row').count(), 636);
  assert.equal(await page.locator('.item-icon img').first().evaluate(i => i.complete && i.naturalWidth > 0), true);
  const initial = await page.evaluate(() => window.api.state());
  assert.equal(initial.layout, 'landscape');
  await page.getByRole('button', { name: '窗口置顶' }).click();
  await page.waitForFunction(pinned => document.querySelector('.pin')?.getAttribute('aria-pressed') === String(!pinned), initial.pinned);
  await app.evaluate(({ BrowserWindow }) => { const w = BrowserWindow.getAllWindows()[0]; w.setBounds({ x: 60, y: 60, width: 840, height: 800 }); });
  // Wait for native resizing, then exercise caption IPC without mouse-position races.
  await page.waitForFunction(() => Math.abs(innerWidth - 840) <= 1 && Math.abs(innerHeight - 800) <= 1);
  await page.evaluate(() => window.api.action('maximize'));
  await page.getByRole('button', { name: '还原', exact: true }).waitFor();
  await page.getByRole('button', { name: '切换竖版', exact: true }).click();
  await page.getByRole('button', { name: '最大化', exact: true }).waitFor();
  await page.waitForFunction(() => Math.abs(innerWidth - 400) <= 1);
  await page.getByRole('button', { name: '切换横版', exact: true }).click();
  await page.waitForFunction(() => innerWidth > 1000);
  await page.getByRole('button', { name: '复制效果文本' }).click();
  assert((await app.evaluate(({ clipboard }) => clipboard.readText())).includes('铁剑在必得（橙色·通用）'));
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '机制', exact: true }).click();
  await page.getByRole('heading', { name: '福佑抽取', exact: true }).waitFor();
  assert.equal(await page.locator('.quality-table tbody tr').count(), 7);
  await page.getByRole('group', { name: '机制主题' }).getByRole('button', { name: '符文选择', exact: true }).click();
  await page.getByRole('button', { name: '查看 36 条符文', exact: true }).click();
  const reference = page.locator('.reference-container:visible');
  assert.equal(await reference.locator('.reference-row').count(), 36);
  await reference.locator('.reference-detail-content .reference-artwork img').evaluate(image => image.decode());
  assert(await reference.locator('.reference-detail-content .reference-artwork img').evaluate(image => image.complete && image.naturalWidth > 0 && image.src.startsWith('file:')));
  await reference.getByRole('button', { name: '复制资料', exact: true }).click();
  const copiedRune = await app.evaluate(({ clipboard }) => clipboard.readText());
  assert(copiedRune.startsWith(await reference.locator('.reference-detail-content h2').textContent()));
  assert(!/(解释参考|日期|查看来源|\b20\d{2}-\d{2}-\d{2}\b)/.test(copiedRune));
  await reference.getByRole('button', { name: '英雄对照 125', exact: true }).click();
  assert.equal(await reference.locator('.reference-row').count(), 125);
  await reference.locator('.reference-detail-content .reference-artwork img').evaluate(image => image.decode());
  assert(await reference.locator('.reference-detail-content .reference-artwork img').evaluate(image => image.complete && image.naturalWidth > 0 && image.src.startsWith('file:') && image.src.includes('/heroes/portraits/')));
  await reference.getByRole('button', { name: '未配置符文池', exact: true }).click();
  assert.equal(await reference.locator('.reference-row').count(), 12);
  await page.getByRole('group', { name: '图鉴分类' }).getByRole('button', { name: '随机事件', exact: true }).click();
  await reference.getByRole('button', { name: '无权重', exact: true }).click();
  assert.equal(await reference.locator('.reference-row').count(), 2);
  await page.getByRole('group', { name: '图鉴分类' }).getByRole('button', { name: '福佑', exact: true }).click();
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  await page.getByRole('button', { name: '模拟器', exact: true }).click();
  await page.getByRole('heading', { name: '福佑模拟器', exact: true }).waitFor();
  assert.equal(await page.evaluate(() => typeof window.api.startCapture), 'undefined');
  assert.equal(await page.evaluate(() => typeof window.api.showOverlay), 'function');
  assert.equal(await page.evaluate(async () => (await window.api.liveState()).active), false);
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 1);
  await page.getByRole('button', { name: '局内', exact: true }).click();
  await page.getByRole('heading', { name: '局内属性', exact: true }).waitFor();
  const overlayWindow = app.waitForEvent('window');
  await page.getByRole('button', { name: '开始采集', exact: true }).click();
  const overlayPage = await overlayWindow;
  overlayPage.on('pageerror', e => errors.push(e.message));
  await overlayPage.getByRole('button', { name: '展开本局属性面板' }).waitFor();
  const screenAnchor = () => app.evaluate(async ({ BrowserWindow }) => {
    const window = BrowserWindow.getAllWindows().find(w => w.webContents.getURL().includes('overlay=1'));
    const orb = await window.webContents.executeJavaScript('JSON.stringify(document.querySelector(".live-orb").getBoundingClientRect())');
    const bounds = window.getBounds(), rect = JSON.parse(orb);
    return { x: bounds.x + rect.x, y: bounds.y + rect.y };
  });
  const assertAnchor = (actual, expected) => { assert(Math.abs(actual.x - expected.x) <= 1 && Math.abs(actual.y - expected.y) <= 1, `Circle drifted: ${JSON.stringify({ actual, expected })}`); };
  const initialAnchor = await screenAnchor();
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().includes('overlay=1'))?.isFocusable()), false);
  const denied = await overlayPage.evaluate(async () => { try { await window.api.startLive({ intervalMs: 1000, hudOnly: true }); return false; } catch { return true; } });
  assert.equal(denied, true, 'Overlay must not start a second capture or mutate readings');
  await overlayPage.getByRole('button', { name: '展开本局属性面板' }).click();
  await overlayPage.locator('.live-overlay').waitFor();
  assertAnchor(await screenAnchor(), initialAnchor);
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().includes('overlay=1'))?.isFocused()), false);
  await overlayPage.evaluate(() => window.api.moveOverlay(120, 90));
  await overlayPage.waitForFunction(async expected => {
    const { layout } = await window.api.overlayState(), rect = document.querySelector('.live-orb').getBoundingClientRect();
    return Math.abs(layout.bounds.x + layout.orb.x - expected.x) <= 1 && Math.abs(layout.bounds.y + layout.orb.y - expected.y) <= 1 && rect.x === layout.orb.x && rect.y === layout.orb.y;
  }, { x: initialAnchor.x + 120, y: initialAnchor.y + 90 });
  const movedAnchor = await screenAnchor();
  assertAnchor(movedAnchor, { x: initialAnchor.x + 120, y: initialAnchor.y + 90 });
  await overlayPage.getByRole('button', { name: '收起本局属性面板' }).click();
  await overlayPage.getByRole('button', { name: '展开本局属性面板' }).waitFor();
  assertAnchor(await screenAnchor(), movedAnchor);
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => !w.webContents.getURL().includes('overlay=1')).minimize());
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().includes('overlay=1'))?.isVisible()), true);
  await overlayPage.getByRole('button', { name: '展开本局属性面板' }).click();
  await overlayPage.locator('.live-overlay').waitFor();
  assertAnchor(await screenAnchor(), movedAnchor);
  await overlayPage.screenshot({ path: 'docs/screenshots/live-overlay-native.png', omitBackground: true });
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => !w.webContents.getURL().includes('overlay=1')).restore());
  await page.waitForFunction(async () => (await window.api.liveState()).status === 'background', undefined, { timeout: 25000 });
  assert.equal(await overlayPage.evaluate(async () => (await window.api.liveState()).active), true);
  assert.equal(await page.locator('.live-record').count(), 0);
  await page.getByRole('button', { name: '暂停采集', exact: true }).click();
  assert.equal(await overlayPage.evaluate(async () => (await window.api.liveState()).active), false);
  const overlayPath = await app.evaluate(({ app }) => app.getPath('userData') + '/overlay.json');
  const overlayClosed = overlayPage.waitForEvent('close');
  await page.evaluate(() => window.api.hideOverlay());
  await overlayClosed;
  const savedAnchor = JSON.parse(await readFile(overlayPath, 'utf8'));
  assertAnchor(savedAnchor, movedAnchor);
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 1);
  await page.getByRole('button', { name: '模拟器', exact: true }).click();
  await page.getByRole('textbox', { name: '搜索模拟福佑' }).fill('攻速鞋');
  await page.locator('.sim-results button').first().click();
  assert.equal(await page.locator('.sim-card').count(), 1);
  await page.getByRole('button', { name: '切换竖版', exact: true }).click();
  await page.waitForFunction(() => Math.abs(innerWidth - 400) <= 1);
  assert.equal(await page.locator('.sim-card').count(), 1);
  const statePath = await app.evaluate(({ app }) => app.getPath('userData') + '/window.json');
  await app.close(); app = undefined;
  const saved = JSON.parse(await readFile(statePath, 'utf8'));
  assert.equal(saved.pinned, !initial.pinned);
  assert(Math.abs(saved.width - 400) <= 1, 'Windows DPI rounding must stay within one DIP');
  assert.equal(saved.layout, 'portrait');
  app = await electron.launch(options);
  const reopened = await app.firstWindow();
  await reopened.locator('.item-row').first().waitFor();
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 1, 'Restart must not start capture or show the overlay');
  const restoredWindow = app.waitForEvent('window');
  await reopened.evaluate(() => window.api.showOverlay());
  const restoredOverlay = await restoredWindow;
  await restoredOverlay.getByRole('button', { name: '展开本局属性面板' }).waitFor();
  assertAnchor(await screenAnchor(), savedAnchor);
  const restoredClosed = restoredOverlay.waitForEvent('close');
  await reopened.evaluate(() => window.api.hideOverlay()); await restoredClosed;
  assert.equal((await reopened.evaluate(() => window.api.state())).pinned, !initial.pinned);
  assert.equal((await reopened.evaluate(() => window.api.state())).layout, 'landscape');
  assert(await app.evaluate(({ BrowserWindow, screen }) => {
    const bounds = BrowserWindow.getAllWindows()[0].getBounds();
    return Math.abs(bounds.width - Math.min(1280, screen.getDisplayMatching(bounds).workArea.width)) <= 1;
  }));
  await reopened.getByRole('button', { name: '窗口置顶' }).click();
  assert.deepEqual(errors, []);
  const message = `PASS Electron${executablePath ? ' packaged' : ''}: landscape startup; portrait/landscape toggle including maximized; simulator retained; portrait exit resets to landscape; pin persistence; catalog/clipboard; mechanics, 36 rune records, 125 hero mappings (12 unconfigured) and missing event weights; live capture off by default; OCR background gate and pause; capture reveals circle; non-focusing vertical overlay with fixed circle through expand/collapse; visible with main minimized; saved position after restart; shared state, sender authorization and close cleanup. No live game data or screen capture.`;
  console.log(message);
  await writeFile(`docs/screenshots/electron${executablePath ? '-packaged' : ''}.txt`, message + '\n');
} finally { if (app) await app.close(); await rm(profile, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }); }
