import { useLayoutEffect, useRef, useState } from 'preact/hooks';
import reference from '../../data/reference.json';
import { qualityShares, runeJudgement, type MechanismTopic } from '../shared/reference';
import { formatValue } from './ReferenceParts';
import './reference.css';

const topics: { id: MechanismTopic; title: string; words: string }[] = [
  { id: 'quality', title: '福佑抽取', words: '品质 概率 等级 保底 蓝 紫 橙 BLESS_QUA' },
  { id: 'costs', title: '重随与重铸', words: '消耗 刷新英雄 避重复 10% REFINE_BLESS_COST' },
  { id: 'runes', title: '符文选择', words: '候选池 提权 机会值 重随 RUNE_CHANCE' },
  { id: 'events', title: '随机事件', words: '发生 权重 70% 30% RANDOM_EVENT_CONFIG' },
  { id: 'basic', title: '基础玩法', words: '开局 奖励 周期 上限 金币 经验 成长 生命 魔法 小兵 树木 MID_' },
];
const configuration = reference.mechanics.bless;
const weights = configuration.quality_probability_BLESS_QUA as Record<string, Record<string, number>>;
const levels = configuration.draw_levels_BLESS_DRAW_LEVELS as Record<string, number>;
const limits = configuration.quality_limit_BLESS_QUA_LIMIT_CFG as Record<string, { min_count: number; max_count: number }>;
const basic = reference.mechanics.basic as { MID_START_GOLD: number; MID_BONUS_GOLD: number; MID_BONUS_XP: number; MID_BONUS_INTERVAL: number; MID_HERO_ATTR_BONUS_TICK: number; MID_HERO_ATTR_BONUS_HP: Record<string, number>; MID_HERO_ATTR_BONUS_MP: Record<string, number>; MID_CREEP_HP_PCT_PER_MIN: number; MID_TREE_REGROW_TIME: number };
const costNames = ['刷新英雄', '重随福佑', '重铸福佑'];
const topicKeys: Record<MechanismTopic, string[]> = {
  quality: Object.keys(configuration).filter(key => /quality|draw|QUA/.test(key)),
  costs: Object.keys(configuration).filter(key => /reroll|recraft/.test(key)).concat(reference.costs.map(cost => cost.key)),
  runes: ['RUNE_CHANCE_MAX_TIMES', 'RUNE_CHANCE_INCREASE', 'RUNE_CONFIG', 'RUNE_POOL', '_pool_max_limit'],
  events: ['RANDOM_EVENT_CONFIG', 'eventCount'], basic: Object.keys(basic),
};
export function Mechanics({ topic, choose, back, openCatalog }: { topic: MechanismTopic; choose: (topic: MechanismTopic) => void; back?: { label: string; action: () => void }; openCatalog: (kind: 'runes' | 'events', pool?: boolean) => void }) {
  const [query, setQuery] = useState(''), [costIndex, setCostIndex] = useState(0), [rerolls, setRerolls] = useState(0);
  const content = useRef<HTMLDivElement>(null), positions = useRef<Partial<Record<MechanismTopic, number>>>({});
  const switchTopic = (next: MechanismTopic) => { if (content.current) positions.current[topic] = content.current.scrollTop; choose(next); };
  useLayoutEffect(() => { if (content.current) content.current.scrollTop = positions.current[topic] || 0; }, [topic]);
  const matches = topics.filter(item => `${item.title} ${item.words} ${topicKeys[item.id].join(' ')}`.toLowerCase().includes(query.trim().toLowerCase()));
  const multiplier = 1 + Math.min(rerolls, reference.mechanics.runeMaxTimes) * reference.mechanics.runeIncrease / 100;
  const cost = reference.costs[costIndex];
  return <main class="mechanics-workspace">
    <div class="mechanics-directory"><label class="mechanics-search">查找机制主题<input type="search" aria-label="查找机制主题" placeholder="概率、消耗、成长…" value={query} onInput={event => setQuery(event.currentTarget.value)}/></label><div class="mechanics-topic-list" role="group" aria-label="机制主题">{matches.map(item => <button key={item.id} aria-pressed={topic === item.id} onClick={() => switchTopic(item.id)}>{item.title}</button>)}</div><label class="mechanics-select">机制主题<select aria-label="选择机制主题" value={topic} onChange={event => switchTopic(event.currentTarget.value as MechanismTopic)}>{topics.map(item => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label>{!matches.length && <p class="reference-muted">没有匹配的主题。<button onClick={() => setQuery('')}>清空搜索</button></p>}</div>
    <div class="mechanics-content" ref={content}><div class="mechanics-heading"><div>{back && <button class="reference-back" onClick={back.action}>{back.label}</button>}<h1>{topics.find(item => item.id === topic)?.title}</h1></div></div>
      {topic === 'quality' && <><p class="mechanics-intro"><b class="num">{Object.keys(levels).length}</b> 次抽取 · 每次 <b class="num">{configuration.draw_count_BLESS_DRAW_COUNT}</b> 选 1</p><section class="mechanics-section"><h2>品质权重占比</h2><table class="reference-table quality-table"><thead><tr><th class="draw-number" scope="col">次数</th><th scope="col">等级</th>{['蓝色', '紫色', '橙色'].map((label, index) => <th class={`quality-cell q${index + 1}`} key={label} scope="col">{label}</th>)}</tr></thead><tbody>{Object.keys(weights).map(draw => <tr key={draw}><th class="draw-number" scope="row">{draw}</th><td><span class="num level-number" title={`第 ${draw} 次抽取`}>{levels[draw]}</span></td>{qualityShares(weights[draw]).map((share, index) => <td class={`quality-cell q${index + 1}`} key={index}>{share === null ? '—' : `${share.toFixed(1)}%`}</td>)}</tr>)}</tbody></table></section><section class="mechanics-section"><h2>品质数量配置</h2><div class="quality-limits">{['蓝色', '紫色', '橙色'].map((label, index) => <div key={label}><span>{label}</span><b class={`quality-cell q${index + 1}`}>{limits[String(index + 1)].min_count}–{limits[String(index + 1)].max_count}</b></div>)}</div><p>对 7 次初始品质安排检查数量上下限。</p></section><div class="reference-links"><button onClick={() => switchTopic('costs')}>查看重随与重铸</button></div></>}
      {topic === 'costs' && <><p class="mechanics-intro">按操作查看第几次的消耗数量。</p><div class="reference-switch" role="group" aria-label="消耗操作">{costNames.map((name, index) => <button key={name} aria-pressed={costIndex === index} onClick={() => setCostIndex(index)}>{name}</button>)}</div><section class="mechanics-section"><h2>{costNames[costIndex]}消耗</h2><table class="reference-table cost-table"><thead><tr><th>次数</th><th>消耗数量</th></tr></thead><tbody>{cost.counts.map(row => <tr key={row.attempt}><th scope="row">第 {row.attempt} 次</th><td class="num">{formatValue(row.amount)}</td></tr>)}</tbody></table></section><section class="mechanics-section"><h2>重随避重复</h2><p>最近 <b class="num">{configuration.reroll_prevent_BLESS_REROLL_PREVENT_COUNTS}</b> 个被重随替换的福佑会进入排除记录。这是避重复记录的长度。</p></section><section class="mechanics-section"><h2>重铸的区间提升</h2><p>最低改善使用重铸区间宽度的 <b class="num">{Math.round(configuration.recraft_increase_rate_BLESS_RECRAFT_INCREASE_RATE * 100)}%</b>，并限制在重铸目标端点；降序区间向更小的目标端点改善。</p></section></>}
      {topic === 'runes' && <><p class="mechanics-intro">查看重随次数怎样提高符文的进池判定值。</p><section class="mechanics-section"><h2>重随提权</h2><p class="mechanics-formula">原始机会值 × (1 + min(次数, {reference.mechanics.runeMaxTimes}) × {reference.mechanics.runeIncrease / 100})</p><label class="reroll-control">重随次数 <output class="num">{rerolls}</output><input type="range" aria-label="符文重随次数" min="0" max={reference.mechanics.runeMaxTimes} step="1" value={rerolls} onInput={event => setRerolls(Number(event.currentTarget.value))}/></label><p>当前倍率 <b class="num">{multiplier.toFixed(1)} 倍</b>，到 {reference.mechanics.runeMaxTimes} 次达到上限。</p><table class="reference-table"><thead><tr><th>原始机会值</th><th>进池判定值</th></tr></thead><tbody>{[10, 100, 110].map(chance => <tr key={chance}><th scope="row">{chance}</th><td class="num">{formatValue(runeJudgement(chance, rerolls, reference.mechanics.runeIncrease, reference.mechanics.runeMaxTimes))}</td></tr>)}</tbody></table></section><section class="mechanics-section"><h2>候选池怎样产生</h2><p>按机会值逐项判定是否进入候选池。</p><p>125 名英雄，113 名有符文池，12 名未配置，共 {reference.pools.length} 组候选池。</p></section><div class="reference-links"><button onClick={() => openCatalog('runes', true)}>查看 {reference.pools.length} 个候选池</button><button onClick={() => openCatalog('runes')}>查看 36 条符文</button></div></>}
      {topic === 'events' && <><p class="mechanics-intro">先按配置决定事件数量，再选择具体事件。</p><section class="mechanics-section"><h2>本局事件数量配置</h2><table class="reference-table"><thead><tr><th>事件数量</th><th>配置概率</th></tr></thead><tbody>{Object.entries(reference.mechanics.eventCounts).map(([count, weight]) => <tr key={count}><th scope="row">{count} 个事件</th><td class="num">{weight}%</td></tr>)}</tbody></table></section><div class="reference-links"><button onClick={() => openCatalog('events')}>查看随机事件资料</button></div></>}
      {topic === 'basic' && <><section class="mechanics-section"><h2>开局与周期资源</h2><table class="reference-table"><tbody>{[['开局金币', basic.MID_START_GOLD, ''], ['周期金币', basic.MID_BONUS_GOLD, '／次'], ['周期经验', basic.MID_BONUS_XP, '／次'], ['周期奖励间隔', Number(basic.MID_BONUS_INTERVAL.toFixed(2)), ' 秒']].map(([label, value, unit]) => <tr key={String(label)}><th scope="row">{label}</th><td class="num">{value}{unit}</td></tr>)}</tbody></table></section><section class="mechanics-section"><h2>生命与魔法上限成长</h2><p>每 <b class="num">{basic.MID_HERO_ATTR_BONUS_TICK}</b> 秒按当前时间阶段累加。</p><table class="reference-table"><thead><tr><th>游戏时间</th><th>生命／次</th><th>魔法／次</th></tr></thead><tbody>{[0, 5, 10, 15, 20, 25].map(minute => <tr key={minute}><th scope="row">{minute === 25 ? '25 分钟起' : `${minute}–${minute + 5} 分钟`}</th><td class="num">{basic.MID_HERO_ATTR_BONUS_HP[String(minute)]}</td><td class="num">{basic.MID_HERO_ATTR_BONUS_MP[String(minute)] ?? basic.MID_HERO_ATTR_BONUS_MP['20']}</td></tr>)}</tbody></table></section><section class="mechanics-section"><h2>地图规则</h2><table class="reference-table"><tbody><tr><th scope="row">小兵生命每分钟额外增长配置</th><td class="num">{basic.MID_CREEP_HP_PCT_PER_MIN}%</td></tr><tr><th scope="row">树木重生时间</th><td class="num">{basic.MID_TREE_REGROW_TIME} 秒</td></tr></tbody></table></section></>}
    </div>
  </main>;
}
